version: "3"
services:
  teamcity-server:
    container_name: receipt-teamcity-server
    image: jetbrains/teamcity-server
    volumes:
      - /receipt/teamcity/data:/data/teamcity_server/datadir
      - /var/log/teamcity:/opt/teamcity/logs
    ports:
      - 8111:8111
    environment:
      - TEAMCITY_SERVER_MEM_OPTS=-Xms300M -Xmx1024M

  teamcity-agent:
    container_name: receipt-teamcity-agent
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=teamcity-server:8111
